// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoSeguroGarantia.Infra.Data.Contexts;

#nullable disable

namespace ProjetoSeguroGarantia.Infra.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240521171330_Inicio")]
    partial class Inicio
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProjetoSeguroGarantia.Domain.Entities.SeguroGarantia", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Beneficiarios")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataHoraCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Exigencias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Finalidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Funcionamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TiposDeProcessos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vantagens")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Guid");

                    b.ToTable("tbl_SeguraGarantia", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
